<script setup>
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { store } from '../../store.js'
import { CheckCircle2, ArrowLeft } from 'lucide-vue-next'
import CreateQuotationModal from './CreateQuotation.vue'

const route = useRoute()
const router = useRouter()
const isBranchUser = computed(() => store.isBranchUser())
const user = computed(() => store.currentUser)
const showEditModal = ref(false)
const showToast = ref(false)
const toastMessage = ref('')

const quoteId = computed(() => route.params.id || route.query.id || 'QT-1882')
const quoteRecord = computed(() => store.getQuotationById(quoteId.value) || (route.query.id ? null : store.quotations[0]))

const branchCurrentTab = ref('Summary')
const branchTabs = ['Summary', 'Items', 'Customer', 'Price', 'Communication', 'Documents', 'Activity']

const branchTabData = computed(() => {
  const q = quoteRecord.value
  const branchName = user.value?.branchName || q?.branch || 'Peshawar'

  const customerName = q?.customer || 'Ahsan Khan'
  const productName = q?.product || 'BRG E-125'
  const quotePrice = q?.total || q?.sellingPrice || q?.value || 'PKR 280,000'
  const quoteStatus = q?.status || 'Sent'

  switch (branchCurrentTab.value) {
    case 'Summary':
      return {
        title: 'Summary',
        items: [
          { label: 'Status', value: quoteStatus },
          { label: 'Customer', value: customerName },
          { label: 'Product', value: productName },
          { label: 'Quantity', value: q?.quantity || '1 unit' },
          { label: 'Quoted Price', value: quotePrice },
          { label: 'Valid Until', value: q?.validTill || q?.validity || '31 Aug 2026' }
        ]
      }
    case 'Items':
      return {
        title: 'Items',
        items: [
          { label: 'Item Name', value: productName },
          { label: 'Specification', value: 'Standard Electric Motor & Battery Pack' },
          { label: 'Inventory Allocation', value: `${branchName} Floor Stock` },
          { label: 'Warranty Plan', value: '1-Year Standard Service' },
          { label: 'Delivery Lead Time', value: 'Within 3 business days' },
          { label: 'Chassis Reservation', value: 'Reserved upon acceptance' }
        ]
      }
    case 'Customer':
      return {
        title: 'Customer',
        items: [
          { label: 'Full Name', value: customerName },
          { label: 'Phone', value: '+92 312 5538198' },
          { label: 'Email', value: `${customerName.toLowerCase().replace(/\s+/g, '.')}@example.com` },
          { label: 'Customer Type', value: 'Retail Individual' },
          { label: 'Branch Association', value: `${branchName} Branch` },
          { label: 'Previous Purchases', value: '1 Completed Unit' }
        ]
      }
    case 'Price':
      return {
        title: 'Price',
        items: [
          { label: 'Base List Price', value: q?.sellingPrice || quotePrice },
          { label: 'Permitted Discount', value: q?.discount || 'PKR 0' },
          { label: 'Net Payable', value: quotePrice },
          { label: 'Tax / Reg Fees', value: 'Included in Quote' },
          { label: 'Payment Terms', value: '100% Advance / Bank Transfer' },
          { label: 'Price Lock Validity', value: '7 Days from generation' }
        ]
      }
    case 'Communication':
      return {
        title: 'Communication',
        items: [
          { label: 'WhatsApp Dispatch', value: 'Sent (Delivered)' },
          { label: 'Email Notification', value: 'Sent to Customer Inbox' },
          { label: 'Customer Follow-up', value: 'Scheduled for Tomorrow 11:00' },
          { label: 'Last Response', value: 'Customer acknowledged quotation' },
          { label: 'Sales Agent', value: 'Hamza (Sales Executive)' },
          { label: 'Call Log', value: 'Initial enquiry verified' }
        ]
      }
    case 'Documents':
      return {
        title: 'Documents',
        items: [
          { label: 'Quotation PDF', value: `${quoteId.value}.pdf` },
          { label: 'Pro-forma Invoice', value: `PI-${quoteId.value.replace('QT-', '')}.pdf` },
          { label: 'Catalogue Brochure', value: 'BRG_Product_Spec.pdf' },
          { label: 'Generated By', value: 'Branch Sales System' },
          { label: 'File Hash / Security', value: 'Verified Digital Stamp' },
          { label: 'Total Attachments', value: '2 Documents' }
        ]
      }
    case 'Activity':
      return {
        title: 'Activity',
        items: [
          { label: '10:30', value: 'Quotation sent to customer via WhatsApp' },
          { label: '09:35', value: 'Quotation generated by sales executive' },
          { label: '09:15', value: 'Customer inquiry received at branch' },
          { label: 'Current State', value: quoteStatus },
          { label: 'Logged By', value: 'System Audit' },
          { label: 'Audit Trail', value: 'Active Scoped Record' }
        ]
      }
    default:
      return {
        title: 'Summary',
        items: []
      }
  }
})

const acceptQuotation = () => {
  if (!quoteRecord.value) return
  quoteRecord.value.status = 'Accepted'
  quoteRecord.value.statusClass = 'bg-[#dcfce7] text-[#165A31]'
  toastMessage.value = `Quotation ${quoteId.value} accepted successfully!`
  showToast.value = true
  setTimeout(() => { showToast.value = false }, 3500)
}

const convertToOrder = () => {
  if (!quoteRecord.value) return
  try {
    const res = store.convertQuotationToOrder(quoteId.value)
    toastMessage.value = `Sales Order ${res.order.id} created from quotation!`
    showToast.value = true
    setTimeout(() => {
      router.push(`/sales/orders/detail?id=${res.order.id}`)
    }, 1200)
  } catch (err) {
    alert(err.message)
  }
}

// Super Admin Data
const activeTab = ref('Summary')
const tabs = ['Summary', 'Items', 'Customer', 'Pricing', 'Communication', 'Documents', 'Activity']
</script>

<template>
  <div v-if="!quoteRecord" class="max-w-[1400px] mx-auto py-16 text-center space-y-4">
    <h2 class="text-2xl font-bold text-gray-900">Quotation Not Found</h2>
    <p class="text-sm text-gray-500">No quotation found with reference "{{ quoteId }}".</p>
    <button @click="router.push('/sales/quotations')" class="inline-flex items-center gap-2 px-4 py-2 bg-[#165A31] text-white text-xs font-bold rounded-lg hover:bg-[#124a28]">
      <ArrowLeft class="w-4 h-4" /> Back to Quotations
    </button>
  </div>

  <!-- BRANCH MANAGER & MAIN VIEW -->
  <div v-else class="max-w-[1400px] mx-auto space-y-6 pb-12">
    <!-- Toast Notification -->
    <div 
      v-if="showToast" 
      class="fixed bottom-5 right-5 z-[110] bg-[#165A31] text-white px-5 py-3 rounded-xl shadow-xl flex items-center gap-3 animate-in slide-in-from-bottom-5 duration-200"
    >
      <CheckCircle2 class="w-5 h-5 text-green-300" />
      <span class="text-xs font-bold">{{ toastMessage }}</span>
    </div>

    <!-- Header -->
    <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 sm:gap-0">
      <div>
        <div class="text-[11px] text-gray-400 mb-1">
          Sales & CRM / Quotations / <span class="font-medium text-gray-600">Quotation {{ quoteId }}</span>
        </div>
        <h1 class="text-[32px] tracking-tight font-bold text-gray-900">Quotation {{ quoteId }}</h1>
        <p class="text-xs text-gray-500 mt-1">Quotation detail — {{ branchCurrentTab }}.</p>
      </div>
      <div class="flex items-center gap-2">
        <button 
          @click="router.push('/sales/quotations')" 
          class="bg-white border border-gray-200 text-gray-700 text-xs font-semibold px-4 py-2 rounded-lg hover:bg-gray-50 transition-colors shadow-sm cursor-pointer"
        >
          Back to List
        </button>
        <button 
          v-if="quoteRecord.status !== 'Accepted'"
          @click="acceptQuotation" 
          class="bg-white border border-[#165A31] text-[#165A31] text-xs font-bold px-4 py-2 rounded-lg hover:bg-[#165A31]/10 transition-colors shadow-sm cursor-pointer"
        >
          Accept Quote
        </button>
        <button 
          @click="convertToOrder" 
          class="bg-[#165A31] text-white text-xs font-bold px-4 py-2 rounded-lg hover:bg-[#124a28] transition-colors shadow-sm cursor-pointer"
        >
          Convert to Sales Order
        </button>
      </div>
    </div>

    <!-- Tabs Navigation Bar -->
    <div class="border-b border-gray-100 flex items-center gap-6 overflow-x-auto pb-1">
      <button 
        v-for="tab in branchTabs" 
        :key="tab"
        @click="branchCurrentTab = tab"
        class="pb-2 text-xs font-semibold whitespace-nowrap transition-colors cursor-pointer relative"
        :class="branchCurrentTab === tab ? 'text-[#165A31] font-bold' : 'text-gray-400 hover:text-gray-700'"
      >
        {{ tab }}
        <div v-if="branchCurrentTab === tab" class="absolute bottom-0 left-0 right-0 h-0.5 bg-[#165A31] rounded-t-full"></div>
      </button>
    </div>

    <!-- Tab Content: Left Box (Data) & Right Box (Related information) -->
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
      <!-- Left Box -->
      <div class="bg-white border border-gray-100 rounded-[12px] shadow-[0_2px_4px_rgba(0,0,0,0.02)] p-6 lg:col-span-8 flex flex-col justify-between">
        <div>
          <h3 class="text-sm font-bold text-gray-900 mb-5">{{ branchTabData.title }}</h3>
          
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div v-for="(item, idx) in branchTabData.items" :key="idx" class="bg-[#fbfcfc] border border-gray-100/80 rounded-lg p-3.5 flex flex-col justify-between">
              <span class="text-[10px] font-medium text-gray-400">{{ item.label }}</span>
              <span class="text-sm font-bold text-gray-900 mt-1">{{ item.value }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Right Box: Related information -->
      <div class="lg:col-span-4 flex flex-col">
        <div class="bg-white border border-gray-100 rounded-[12px] shadow-[0_2px_4px_rgba(0,0,0,0.02)] p-6">
          <h3 class="text-sm font-bold text-gray-900 mb-5">Related information</h3>
          
          <div class="grid grid-cols-2 gap-3">
            <div class="bg-[#fbfcfc] border border-gray-100/80 rounded-lg p-3.5 flex flex-col justify-between">
              <span class="text-[10px] font-medium text-gray-400">Owner</span>
              <span class="text-sm font-bold text-gray-900 mt-1">Hamza</span>
            </div>
            <div class="bg-[#fbfcfc] border border-gray-100/80 rounded-lg p-3.5 flex flex-col justify-between">
              <span class="text-[10px] font-medium text-gray-400">Last Contact</span>
              <span class="text-sm font-bold text-gray-900 mt-1">Today 09:35</span>
            </div>
            <div class="bg-[#fbfcfc] border border-gray-100/80 rounded-lg p-3.5 flex flex-col justify-between">
              <span class="text-[10px] font-medium text-gray-400">Document</span>
              <span class="text-sm font-bold text-gray-900 mt-1">{{ quoteId }}.pdf</span>
            </div>
            <div class="bg-[#fbfcfc] border border-gray-100/80 rounded-lg p-3.5 flex flex-col justify-between">
              <span class="text-[10px] font-medium text-gray-400">Activity</span>
              <span class="text-sm font-bold text-gray-900 mt-1" :class="quoteRecord.status === 'Accepted' ? 'text-[#165A31]' : ''">{{ quoteRecord.status || 'Sent' }}</span>
            </div>
          </div>
        </div>
        
        <p class="text-[11px] text-gray-400 font-medium mt-3 px-1">
          Scoped to {{ user?.branchName || 'Peshawar' }} Branch. Converting to Sales Order automatically reserves floor stock and locks pricing.
        </p>
      </div>
    </div>

    <!-- Edit Quotation Modal Popup -->
    <CreateQuotationModal 
      v-if="showEditModal" 
      :is-modal="true" 
      :quotation="quoteRecord" 
      @close="showEditModal = false" 
    />
  </div>
</template>
