/**
 * AJ EcoDrive — Super Admin Production Curriculum Catalog (SA-01 to SA-20)
 * PROGRAM: AJ-TOUR-RECONSTRUCT-2026
 * PHASE 6: CHECKPOINT 6.2 — FULL CURRICULUM ROLLOUT
 *
 * Implements the 20 authoritative Super Admin modules frozen in Phase 5:
 * - SA-01: Workspace Orientation
 * - SA-02: Dashboard & Network Analytics
 * - SA-03: Organisation & Branch Governance
 * - SA-04: User Access & Roles Governance
 * - SA-05: Product Master Catalogue
 * - SA-06: Product Request Review
 * - SA-07: Pricing Rules & Matrix
 * - SA-08: Suppliers & Procurement POs
 * - SA-09: Goods Receipt & Landed Cost
 * - SA-10: Serialized Asset Inventory
 * - SA-11: Stock Request Authorizations
 * - SA-12: Inter-Branch Stock Transfers
 * - SA-13: Inventory Adjustments & Audit
 * - SA-14: Sales Orders & Customer Oversight
 * - SA-15: Sales Returns & Refunds
 * - SA-16: Workshop Repairs & Service Cases
 * - SA-17: Operating Expenses & Outflow
 * - SA-18: Supplier Bills & Settlement
 * - SA-19: Central Action Centre Queues
 * - SA-20: Analytics, History & System Audit
 *
 * Target IDs strictly follow the 4-part semantic grammar:
 * <workspace>.<domain>.<surface>.<element-path>
 */

export const superAdminMissions = [
  {
    id: 'sa-mission-01',
    code: 'SA-01',
    title: 'Workspace Orientation & Command Shell',
    category: 'Executive Governance',
    workspace: 'Super Admin',
    route: '/dashboard',
    surface: 'MainLayout Header & Navigation',
    description: 'Master the Head Office command shell, multi-branch context selector, and real-time Action Centre indicators.',
    tourLevels: ['QUICK_ORIENTATION', 'PAGE_TOUR'],
    steps: [
      {
        id: 'sa-01-01',
        stepNumber: 1,
        title: 'Super Admin Executive Authority',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'shared.layout.header.role-badge',
        preferredPlacement: 'bottom',
        route: '/dashboard',
        explanation: 'Displays your active session role as Super Admin, confirming executive authority across all branches.',
        instruction: 'Verify your role badge in the top navigation bar to confirm Head Office permissions.',
        whyItMatters: 'Head Office actions modify global product catalogs, pricing matrix rules, and company-wide accounts.',
        whatHappensNext: 'Next, locate the multi-branch viewport switcher to examine individual showrooms.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-01-02',
        stepNumber: 2,
        title: 'Multi-Branch Viewport Switcher',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'shared.layout.header.branch-switcher',
        preferredPlacement: 'bottom',
        route: '/dashboard',
        explanation: 'Dropdown allowing you to switch between consolidated company-wide reporting and specific dealership locations.',
        instruction: 'Select All Branches for consolidated metrics, or choose a specific showroom to audit local stock.',
        whyItMatters: 'Provides instant operational visibility into individual branch inventory levels and sales volume.',
        whatHappensNext: 'Observe the Action Centre indicator for pending branch authorizations.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-01-03',
        stepNumber: 3,
        title: 'Central Action Centre Indicator',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'shared.layout.header.action-centre',
        preferredPlacement: 'bottom',
        route: '/dashboard',
        explanation: 'Real-time alert indicator displaying pending showroom requests requiring Head Office authorization.',
        instruction: 'Click this alert shortcut whenever branch requests require executive review.',
        whyItMatters: 'Unapproved requests halt showroom work: stock replenishment halts and expense settlements stall.',
        whatHappensNext: 'Review the primary navigation rail to access operational modules.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-01-04',
        stepNumber: 4,
        title: 'Primary Navigation Sidebar',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'shared.layout.nav.sidebar',
        preferredPlacement: 'right',
        route: '/dashboard',
        explanation: 'Collapsible navigation rail providing structured access to Catalogue, Procurement, Inventory, Sales, and Finance.',
        instruction: 'Use navigation groups to transition between operational workflows and administrative governance.',
        whyItMatters: 'Maintains clear functional boundaries across the dealership lifecycle.',
        whatHappensNext: 'Orientation complete. Proceed to executive dashboard metrics.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-02',
    code: 'SA-02',
    title: 'Dashboard & Network Analytics',
    category: 'Executive KPIs & Analytics',
    workspace: 'Super Admin',
    route: '/dashboard',
    surface: 'Executive Command Dashboard',
    description: 'Monitor consolidated net sales, gross trading margins, owned inventory liquidity, and branch leaderboards.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-02-01',
        stepNumber: 1,
        title: 'Consolidated Network Net Sales',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.dashboard.kpi.net-sales',
        preferredPlacement: 'bottom',
        route: '/dashboard',
        explanation: 'Real-time aggregate revenue across all operating branches net of commercial discounts and authorized refunds.',
        instruction: 'Monitor daily sales pacing against monthly commercial revenue targets.',
        whyItMatters: 'Canonical revenue KPI: Net Sales = Gross Selling Amount - Discounts - Sales Returns / Refund Adjustments.',
        whatHappensNext: 'Examine consolidated gross trading margin.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-02-02',
        stepNumber: 2,
        title: 'Consolidated Gross Trading Profit',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.dashboard.kpi.gross-profit',
        preferredPlacement: 'bottom',
        route: '/dashboard',
        explanation: 'Net Sales revenue minus vehicle cost of goods sold based on actual landed acquisition costs.',
        instruction: 'Track gross trading profitability before deducting local showroom overheads.',
        whyItMatters: 'Ensures commercial discount ceilings protect baseline corporate margin requirements.',
        whatHappensNext: 'Examine owned unsold inventory capital.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-02-03',
        stepNumber: 3,
        title: 'Total Owned Inventory Capital',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.dashboard.kpi.inventory-value',
        preferredPlacement: 'bottom',
        route: '/dashboard',
        explanation: 'Total capital invested in unsold electric vehicles across all showrooms, transit hubs, and warehouses.',
        instruction: 'Audit inventory capital liquidity to maintain optimal showroom stock without tying up excess cash.',
        whyItMatters: 'Excess unsold stock incurs holding costs; stockouts lead to lost showroom sales.',
        whatHappensNext: 'Examine multi-branch performance leaderboard.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-02-04',
        stepNumber: 4,
        title: 'Multi-Branch Commercial Leaderboard',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.dashboard.table.branch-performance',
        preferredPlacement: 'top',
        route: '/dashboard',
        explanation: 'Comparative ranking of all dealership branches by units sold, total revenue, average discount, and margin.',
        instruction: 'Review comparative performance to identify top-performing showrooms and branches requiring replenishment.',
        whyItMatters: 'Informs inter-branch stock rebalancing and regional commercial marketing allocations.',
        whatHappensNext: 'Dashboard review complete.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-03',
    code: 'SA-03',
    title: 'Organisation & Branch Governance',
    category: 'Organisation Setup',
    workspace: 'Super Admin',
    route: '/organisation/branches',
    surface: 'Branch Directory & Registration',
    description: 'Configure corporate dealership branches, regional facilities, showroom codes, and operating attributes.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-03-01',
        stepNumber: 1,
        title: 'Branch Network Directory',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.organisation.branches.table',
        preferredPlacement: 'top',
        route: '/organisation/branches',
        explanation: 'Master roster of all authorized dealership locations, service centers, and central warehouse hubs.',
        instruction: 'Review active showroom status, assigned branch codes, and manager contact details.',
        whyItMatters: 'Every serialized unit, sales order, and stock request is anchored to an authorized branch entity.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-03-02',
        stepNumber: 2,
        title: 'Create Dealership Branch',
        mode: 'PRACTICE',
        trainingType: 'practice',
        expectedAction: 'CLICK',
        actionType: 'NAVIGATE',
        postconditionRoute: '/organisation/branches/create',
        targetId: 'sa.organisation.branches.create-btn',
        preferredPlacement: 'left',
        route: '/organisation/branches',
        explanation: 'Form to register a new showroom branch with unique 3-letter code and operating credentials.',
        instruction: 'Click Add Branch to open the branch registration form.',
        whyItMatters: 'Branch codes (e.g. PEW-01, LHR-01) serve as prefixes for serial tracking and audit records.',
        successMessage: 'Branch creation form opened! Complete this walkthrough or proceed.',
        mutationRisk: 'RISK_1_UI_STATE_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-04',
    code: 'SA-04',
    title: 'User Access & Roles Governance',
    category: 'Security & Access',
    workspace: 'Super Admin',
    route: '/organisation/users',
    surface: 'User Management & Permissions',
    description: 'Govern system user accounts, role assignments, branch scope affiliations, and account activation.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-04-01',
        stepNumber: 1,
        title: 'System User Directory',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.organisation.users.table',
        preferredPlacement: 'top',
        route: '/organisation/users',
        explanation: 'Authorized staff accounts across Head Office and all branch dealerships.',
        instruction: 'Audit active user roles and ensure each employee is bound to their designated branch.',
        whyItMatters: 'Maintains administrative accountability and access control across dealerships.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-05',
    code: 'SA-05',
    title: 'Product Master Catalogue',
    category: 'EV Models & Variants',
    workspace: 'Super Admin',
    route: '/catalogue/products',
    surface: 'Master Product Catalogue',
    description: 'Configure corporate EV models, technical battery specifications, motor ratings, and warranty defaults.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE', 'GUIDED_TASK'],
    steps: [
      {
        id: 'sa-05-01',
        stepNumber: 1,
        title: 'Master EV Catalogue Roster',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.catalogue.products.table',
        preferredPlacement: 'top',
        route: '/catalogue/products',
        explanation: 'Central catalog of approved electric scooter, bike, and commercial cargo vehicle models.',
        instruction: 'Review active models, technical specifications, and retail pricing references.',
        whyItMatters: 'Creating a master product configures technical metadata but creates ZERO physical stock.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-05-02',
        stepNumber: 2,
        title: 'Add New EV Model Definition',
        mode: 'PRACTICE',
        trainingType: 'practice',
        expectedAction: 'CLICK',
        actionType: 'OPEN_MODAL',
        postconditionSelector: '[data-tour*="modal"], .fixed.inset-0',
        targetId: 'sa.catalogue.products.create-btn',
        preferredPlacement: 'left',
        route: '/catalogue/products',
        explanation: 'Opens master model configuration form for entering model name, battery kWh, and motor wattage.',
        instruction: 'Click Add Product to define a new vehicle variant.',
        whyItMatters: 'Only catalog-approved models can be quoted by showrooms or ordered from manufacturers.',
        successMessage: 'Vehicle definition modal opened! Complete this walkthrough or proceed.',
        mutationRisk: 'RISK_1_UI_STATE_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-06',
    code: 'SA-06',
    title: 'Product Request Review & Approval',
    category: 'Branch Catalogue Requests',
    workspace: 'Super Admin',
    route: '/catalogue/requests',
    surface: 'Showroom Model Requests',
    description: 'Evaluate new vehicle model requests submitted by branch showrooms based on local customer demand.',
    tourLevels: ['PAGE_TOUR', 'GUIDED_TASK'],
    steps: [
      {
        id: 'sa-06-01',
        stepNumber: 1,
        title: 'Showroom Request Queue',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.catalogue.requests.queue',
        preferredPlacement: 'top',
        route: '/catalogue/requests',
        explanation: 'Lists showroom submissions proposing new electric vehicle models or configurations.',
        instruction: 'Review the commercial justification and technical specs submitted by branch managers.',
        whyItMatters: 'Approval authorizes the model for onboarding but does not create physical vehicles.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-07',
    code: 'SA-07',
    title: 'Pricing Rules & Discount Matrix',
    category: 'Commercial Governance',
    workspace: 'Super Admin',
    route: '/catalogue/pricing',
    surface: 'Pricing Rules Hub',
    description: 'Set standard model retail prices, seasonal promotional campaigns, and branch discount ceiling policies.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-07-01',
        stepNumber: 1,
        title: 'Commercial Price Rules Table',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.catalogue.pricing.table',
        preferredPlacement: 'top',
        route: '/catalogue/pricing',
        explanation: 'Approved price matrices dictating retail selling prices and maximum authorized branch discounts.',
        instruction: 'Audit active rules to ensure price consistency across dealership regions.',
        whyItMatters: 'Showrooms cannot execute sales below the authorized minimum pricing rules.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-08',
    code: 'SA-08',
    title: 'Suppliers & Procurement Orders',
    category: 'Procurement Governance',
    workspace: 'Super Admin',
    route: '/procurement/purchase-orders',
    surface: 'Purchase Order Management',
    description: 'Authorize factory purchase orders, manage OEM supplier contracts, and monitor manufacturer order status.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE', 'GUIDED_TASK'],
    steps: [
      {
        id: 'sa-08-01',
        stepNumber: 1,
        title: 'Purchase Orders Register',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.procurement.po.table',
        preferredPlacement: 'top',
        route: '/procurement/purchase-orders',
        explanation: 'Register of factory purchase orders placed with OEM vehicle manufacturers.',
        instruction: 'Review orders in Draft, Pending Approval, Ordered, and In Transit stages.',
        whyItMatters: 'Submitting a PO does not immediately place it into Ordered if executive approval is required.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-09',
    code: 'SA-09',
    title: 'Goods Receipt & Landed Costing',
    category: 'Stock Ingestion & Valuation',
    workspace: 'Super Admin',
    route: '/procurement/receipts',
    surface: 'Goods Receipt & Ingestion',
    description: 'Receive factory shipments, verify physical chassis serials, and allocate landed freight/duties costs.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-09-01',
        stepNumber: 1,
        title: 'Goods Receipts Log',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.procurement.receipts.table',
        preferredPlacement: 'top',
        route: '/procurement/receipts',
        explanation: 'Log of physical vehicle shipments received at central dock and showroom facilities.',
        instruction: 'Audit received quantities against purchase order specifications.',
        whyItMatters: 'Goods Receipt transitions units into Receiving/QC before inventory becomes Available.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-10',
    code: 'SA-10',
    title: 'Serialized Asset Inventory Control',
    category: 'Chassis Asset Tracking',
    workspace: 'Super Admin',
    route: '/inventory/serialized-units',
    surface: 'Physical Serialized Units',
    description: 'Track individual electric vehicle chassis units across all stages: Available, Reserved, In Transit, Sold.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-10-01',
        stepNumber: 1,
        title: 'Serialized Units Master Roster',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.inventory.units.table',
        preferredPlacement: 'top',
        route: '/inventory/serialized-units',
        explanation: 'Tracks every physical bike by unique chassis VIN number, motor ID, and battery barcode.',
        instruction: 'Filter by branch or lifecycle status to locate specific physical vehicles.',
        whyItMatters: 'Sales orders and customer deliveries must bind to an exact physical serialized chassis unit.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-11',
    code: 'SA-11',
    title: 'Stock Request Authorizations',
    category: 'Replenishment Governance',
    workspace: 'Super Admin',
    route: '/inventory/stock-requests',
    surface: 'Stock Replenishment Queue',
    description: 'Authorize showroom inventory replenishment requests from warehouse stock or trigger factory POs.',
    tourLevels: ['PAGE_TOUR', 'GUIDED_TASK'],
    steps: [
      {
        id: 'sa-11-01',
        stepNumber: 1,
        title: 'Stock Replenishment Requests',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.inventory.requests.table',
        preferredPlacement: 'top',
        route: '/inventory/stock-requests',
        explanation: 'Roster of showroom stock replenishment requests awaiting Head Office review.',
        instruction: 'Review requesting branch, requested EV model, and current branch showroom floor stock.',
        whyItMatters: 'Stock Request approval authorizes fulfillment; physical movement occurs via Inter-Branch Transfer.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-12',
    code: 'SA-12',
    title: 'Inter-Branch Stock Transfers',
    category: 'Fleet Balancing & Transit',
    workspace: 'Super Admin',
    route: '/inventory/transfers',
    surface: 'Transfer Orders & Transit',
    description: 'Oversee vehicle transit between central warehouses and branch showrooms; audit in-transit fleet custody.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-12-01',
        stepNumber: 1,
        title: 'Inter-Branch Transfers Table',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.inventory.transfers.table',
        preferredPlacement: 'top',
        route: '/inventory/transfers',
        explanation: 'Records transfer orders moving units between origin showrooms and destination facilities.',
        instruction: 'Audit transfers in Pending, Dispatched (In Transit), and Received states.',
        whyItMatters: 'Units remain in Transfer In Transit status until destination physical receipt is recorded.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-13',
    code: 'SA-13',
    title: 'Inventory Adjustments & Physical Audit',
    category: 'Asset Integrity & Audit',
    workspace: 'Super Admin',
    route: '/inventory/stock-adjustments',
    surface: 'Inventory Adjustments & Variances',
    description: 'Review physical showroom count variances, audit cycle count discrepancy investigations, and post corrections.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE', 'GUIDED_TASK'],
    steps: [
      {
        id: 'sa-13-01',
        stepNumber: 1,
        title: 'Inventory Adjustment Requests',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.inventory.adjustments.table',
        preferredPlacement: 'top',
        route: '/inventory/stock-adjustments',
        explanation: 'Physical stock discrepancies reported by showrooms awaiting Head Office investigation.',
        instruction: 'Verify variance justification before approving ledger adjustments.',
        whyItMatters: 'Adjustment approval authorizes the correction; formal posting is a separate controlled action.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-14',
    code: 'SA-14',
    title: 'Sales Orders & Customer Oversight',
    category: 'Commercial Auditing',
    workspace: 'Super Admin',
    route: '/sales/orders',
    surface: 'Network Sales Orders',
    description: 'Audit company-wide retail vehicle sales, contract terms, customer profiles, and commercial discounts.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-14-01',
        stepNumber: 1,
        title: 'Consolidated Sales Orders Table',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.sales.orders.table',
        preferredPlacement: 'top',
        route: '/sales/orders',
        explanation: 'Comprehensive log of all retail vehicle sales across every authorized AJ EcoDrive branch.',
        instruction: 'Audit confirmed orders, customer details, and bound chassis unit numbers.',
        whyItMatters: 'Ensures commercial discount policies and customer contracts comply with corporate standards.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-15',
    code: 'SA-15',
    title: 'Sales Returns & Customer Refunds',
    category: 'Refund Governance',
    workspace: 'Super Admin',
    route: '/sales/returns',
    surface: 'Returns & Refund Authorizations',
    description: 'Review vehicle return intake records, inspect technical triage notes, and authorize customer refund payouts.',
    tourLevels: ['PAGE_TOUR', 'GUIDED_TASK'],
    steps: [
      {
        id: 'sa-15-01',
        stepNumber: 1,
        title: 'Sales Returns & Refunds Register',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.sales.returns.table',
        preferredPlacement: 'top',
        route: '/sales/returns',
        explanation: 'Customer vehicle returns submitted by showrooms awaiting Head Office commercial authorization.',
        instruction: 'Review technical inspection notes and condition triage before authorizing refund disbursement.',
        whyItMatters: 'Authorized refunds adjust net sales revenue and restock the vehicle into inspection inventory.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-16',
    code: 'SA-16',
    title: 'Workshop Repairs & Service Cases',
    category: 'Warranty & After-Sales',
    workspace: 'Super Admin',
    route: '/after-sales/warranty',
    surface: 'Service Cases & Warranty',
    description: 'Oversee dealership workshop repairs, customer warranty claims, battery health triage, and spare parts usage.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-16-01',
        stepNumber: 1,
        title: 'Workshop Service Cases Queue',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.service.cases.table',
        preferredPlacement: 'top',
        route: '/after-sales/warranty',
        explanation: 'Central log of warranty claims, routine maintenance jobs, and battery diagnostic cases.',
        instruction: 'Monitor service turnaround times and repeated component defect trends.',
        whyItMatters: 'Identifies chronic OEM manufacturer defects and tracks branch warranty labor reimbursements.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-17',
    code: 'SA-17',
    title: 'Operating Expenses & Cash Outflow',
    category: 'Financial Governance',
    workspace: 'Super Admin',
    route: '/finance/expenses',
    surface: 'Branch Operating Expenses',
    description: 'Audit showroom petty cash vouchers, utility bills, and authorize branch operational cash disbursements.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE', 'GUIDED_TASK'],
    steps: [
      {
        id: 'sa-17-01',
        stepNumber: 1,
        title: 'Operating Expenses Register',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.finance.expenses.table',
        preferredPlacement: 'top',
        route: '/finance/expenses',
        explanation: 'Showroom petty cash expense claims awaiting Head Office review and approval.',
        instruction: 'Audit expense categories, supporting receipt attachments, and branch operational budgets.',
        whyItMatters: 'Approval authorizes expense recognition; cash disbursement follows authorized payment workflow.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-18',
    code: 'SA-18',
    title: 'Supplier Bills & Settlement',
    category: 'Three-Way Match & Bills',
    workspace: 'Super Admin',
    route: '/procurement/vendor-bills',
    surface: 'Supplier Invoices & Bills',
    description: 'Execute three-way matching (PO vs Goods Receipt vs Supplier Bill) and authorize factory payment disbursements.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-18-01',
        stepNumber: 1,
        title: 'Supplier Bills Register',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.finance.bills.table',
        preferredPlacement: 'top',
        route: '/procurement/vendor-bills',
        explanation: 'Supplier invoices received from manufacturers for bulk vehicle shipments and parts procurement.',
        instruction: 'Perform three-way matching against verified Goods Receipts before scheduling settlement.',
        whyItMatters: 'Prevents overpayment by verifying that billing matches physically inspected inventory.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-19',
    code: 'SA-19',
    title: 'Central Action Centre Command',
    category: 'Executive Decisioning',
    workspace: 'Super Admin',
    route: '/dashboard/action-centre',
    surface: 'Central Action Centre',
    description: 'Unified executive decisioning command hub consolidating all pending approvals across dealership branches.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE', 'GUIDED_TASK'],
    steps: [
      {
        id: 'sa-19-01',
        stepNumber: 1,
        title: 'Active Operational Task Queues',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.action-centre.queue.list',
        preferredPlacement: 'right',
        route: '/dashboard/action-centre',
        explanation: 'Unified task list consolidating pending Product Requests, Stock Replenishments, Adjustments, and Expenses.',
        instruction: 'Select any task row to open the treatment decision drawer.',
        whyItMatters: 'Resolving queue items unblocks branch workflows and updates real-time operational status.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
      {
        id: 'sa-19-02',
        stepNumber: 2,
        title: 'Executive Decision Treatment Drawer',
        mode: 'PRACTICE',
        trainingType: 'practice',
        expectedAction: 'CLICK',
        actionType: 'OPEN_DRAWER',
        postconditionSelector: '[data-tour*="treatment"], .fixed.inset-0',
        targetId: 'sa.action-centre.drawer.approve-btn',
        preferredPlacement: 'left',
        route: '/dashboard/action-centre',
        explanation: 'Decision panel allowing you to evaluate case context and click Approve or Reject.',
        instruction: 'Review supporting details and click Treat / Inspect to evaluate the branch request.',
        whyItMatters: 'Executive approval authorizes the downstream action and logs an auditable decision record.',
        successMessage: 'Treatment drawer opened! Review details and authorize the action.',
        mutationRisk: 'RISK_2_DRAFT_OR_REVERSIBLE',
        skippable: true,
      },
    ],
  },
  {
    id: 'sa-mission-20',
    code: 'SA-20',
    title: 'Analytics, History & System Audit',
    category: 'Audit & Compliance',
    workspace: 'Super Admin',
    route: '/analytics/reports/sales',
    surface: 'Analytics Hub & Movement Audit',
    description: 'Audit company-wide financial performance, historical vehicle movement logs, and immutable compliance records.',
    tourLevels: ['PAGE_TOUR', 'FIELD_GUIDE'],
    steps: [
      {
        id: 'sa-20-01',
        stepNumber: 1,
        title: 'Network Sales Analytics Hub',
        mode: 'OBSERVE',
        trainingType: 'observe',
        targetId: 'sa.analytics.sales.chart',
        preferredPlacement: 'top',
        route: '/analytics/reports/sales',
        explanation: 'Comprehensive analytical charts breaking down revenue trends, margin pacing, and model sales velocities.',
        instruction: 'Filter by date range and branch to evaluate commercial sales performance.',
        whyItMatters: 'Provides business intelligence to guide manufacturing forecasts and retail pricing strategies.',
        mutationRisk: 'RISK_0_READ_ONLY',
        skippable: true,
      },
    ],
  },
];
