/**
 * AJ EcoDrive — Cross-Role Guided Scenarios (SCENARIO-A to SCENARIO-F)
 * PROGRAM: AJ-TOUR-RECONSTRUCT-2026
 * PHASE 6: CHECKPOINT 6.2 FINAL CLOSURE & CHECKPOINT 6.3/6.4
 *
 * Implements the 6 cross-role guided scenarios frozen in Phase 5:
 * - SCENARIO-A: New Product Introduction & Request Lifecycle
 * - SCENARIO-B: Stock Replenishment & Fulfillment Decision Routing (Both Branches: Transfer vs PO)
 * - SCENARIO-C: End-to-End Procurement Lifecycle (5 Distinct Stages)
 * - SCENARIO-D: Sell an Electric Vehicle (Quotation & Direct POS paths, Reservation, Payment, Handover)
 * - SCENARIO-E: Controlled Inventory Discrepancy (Discovery -> Review/Approval -> Separate Posting)
 * - SCENARIO-F: Operating Expense Authorization (Submission -> Review/Approval -> Separate Payout)
 *
 * Business Invariants:
 * 1. Product Request Approval != Product Creation. Product activation creates 0 physical stock.
 * 2. Quotation does NOT reserve stock. Confirmed Order + Chassis Selection = Reserved.
 * 3. Procurement has 5 distinct stages: PO != Goods Receipt != Landed Cost != Supplier Bill != Supplier Payment.
 * 4. Cycle Count != Adjustment. Adjustment Approval != Posting (separate operational steps).
 * 5. Expense Approval != Payment / Cash Outflow (separate disbursement step).
 * 6. Explicit role handoffs: Workspaces are 'Super Admin' and 'Branch Manager'. No auto-switching auth.
 * 7. Canonical mutation risks: RISK_0_READ_ONLY, RISK_1_UI_STATE_ONLY, RISK_2_DRAFT_OR_REVERSIBLE, RISK_3_BUSINESS_RECORD_MUTATION, RISK_4_SENSITIVE_OR_IRREVERSIBLE.
 */

export const crossRoleScenarios = [
  {
    id: 'scenario-a',
    code: 'SCENARIO-A',
    title: 'New Product Request & Master Catalog Activation',
    category: 'Product & Catalog Governance',
    description: 'Walk through showroom product request intake, Head Office evaluation, catalog entry creation, and zero-stock awareness.',
    segments: [
      {
        id: 'scenario-a-seg-1',
        segmentNumber: 1,
        title: 'Branch Product Demand Request',
        workspace: 'Branch Manager',
        route: '/inventory/product-requests',
        surface: 'Product Requests Queue',
        targetId: 'bm.inventory.product-requests.action-create-request',
        explanation: 'Showrooms submit a structured Product Request when customer demand or new EV models are requested by walk-in buyers.',
        instruction: 'Initiate a new product request with model specifications and initial market feedback.',
        whyItMatters: 'Branch Managers cannot directly create catalog products; centralized governance ensures uniform specifications and compliance.',
        whatHappensNext: 'The request is forwarded to the Head Office Action Centre.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_2_DRAFT_OR_REVERSIBLE',
      },
      {
        id: 'scenario-a-seg-2',
        segmentNumber: 2,
        title: 'Head Office Catalog Review & Activation',
        workspace: 'Super Admin',
        route: '/inventory/product-requests',
        surface: 'Action Centre - Product Requests',
        targetId: 'sa.inventory.product-requests.action-approve-request',
        explanation: 'Super Admin reviews product specifications, validates supplier feasibility, and approves catalog inclusion.',
        instruction: 'Review the technical specs and approve the product request for master catalog creation.',
        whyItMatters: 'Approving the request does NOT create stock; it authorizes catalog definition and subsequent procurement.',
        whatHappensNext: 'Product Master entry is published; procurement purchase orders can now reference this model.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
    ],
    handoff: {
      fromRole: 'Branch Manager',
      toRole: 'Super Admin',
      title: 'Handoff to Head Office Catalog Governance',
      whatYouCompleted: 'Drafted and submitted a branch product request for the requested EV model specification.',
      whatChanged: 'Product request status is now PENDING_REVIEW in the central Action Centre queue.',
      nextOwner: 'Super Admin / Head Office Catalog Administrator',
      whatNextOwnerDoes: 'Validates OEM technical homologation, defines pricing matrix tiers, and creates the master product record.',
      whatHasNotHappenedYet: 'No physical inventory exists, and the model is not yet available for customer quotation.',
      whatYouShouldCheckNext: 'Monitor the Product Requests queue status until approved and published into the showroom catalog.',
    },
    debrief: {
      recordImpact: 'Product Request marked APPROVED; Master Product SKU created in central catalog.',
      stockImpact: 'ZERO physical units created. Physical units only enter through Purchase Order Goods Receipt.',
      moneyImpact: 'Zero financial journal postings at this stage. Cost of Goods Sold is recognized upon unit sale.',
      customerOrderImpact: 'Showroom staff can now draft quotations and book orders once inventory is allocated or ordered.',
      nextOwner: 'Procurement Specialist / Super Admin to raise supplier Purchase Order.',
      nextCheck: 'Verify that the new model appears in the active Products catalog with correct specifications.',
    },
  },

  {
    id: 'scenario-b',
    code: 'SCENARIO-B',
    title: 'Stock Replenishment & Decision Routing',
    category: 'Inventory & Logistics',
    description: 'Learn how branch inventory depletion triggers replenishment requests, followed by Head Office transfer routing or supplier procurement.',
    segments: [
      {
        id: 'scenario-b-seg-1',
        segmentNumber: 1,
        title: 'Branch Stock Depletion & Request Creation',
        workspace: 'Branch Manager',
        route: '/inventory/stock-requests',
        surface: 'Stock Requests Management',
        targetId: 'bm.inventory.stock-requests.action-create-request',
        explanation: 'Showrooms generate Stock Replenishment Requests when floor models or fast-moving spares fall below showroom stocking targets.',
        instruction: 'Draft a replenishment request specifying required model and quantity.',
        whyItMatters: 'Stock request approval is NOT a transfer approval; it initiates Head Office allocation review.',
        whatHappensNext: 'Head Office evaluates stock across sister branches before deciding between inter-branch transfer or supplier PO.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_2_DRAFT_OR_REVERSIBLE',
      },
      {
        id: 'scenario-b-seg-2',
        segmentNumber: 2,
        title: 'Head Office Allocation & Decision Routing',
        workspace: 'Super Admin',
        route: '/inventory/stock-requests',
        surface: 'Stock Requests Action Centre',
        targetId: 'sa.inventory.stock-requests.action-route-transfer',
        explanation: 'Super Admin inspects network-wide warehouse and branch stock to determine if stock is available elsewhere.',
        instruction: 'Review inventory availability and approve routing as Inter-Branch Transfer or escalate to Procurement PO.',
        whyItMatters: 'Branch 1: If sister branches hold surplus stock, route as Inter-Branch Transfer. Branch 2: If stock is exhausted network-wide, escalate to supplier PO.',
        whatHappensNext: 'Transfer order created in Transfer In Transit workflow, or PO initiated with supplier.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
    ],
    handoff: {
      fromRole: 'Branch Manager',
      toRole: 'Super Admin',
      title: 'Handoff to Network Inventory Coordinator',
      whatYouCompleted: 'Submitted replenishment request with required EV models and urgency level.',
      whatChanged: 'Stock request status set to SUBMITTED and queued in central logistics.',
      nextOwner: 'Super Admin / Supply Chain Manager',
      whatNextOwnerDoes: 'Runs network inventory availability check and assigns fulfillment route (Transfer vs PO).',
      whatHasNotHappenedYet: 'Stock has not moved and no chassis has been reserved for your branch.',
      whatYouShouldCheckNext: 'Check stock request tracking status for dispatch notification or PO allocation.',
    },
    debrief: {
      recordImpact: 'Stock request approved and assigned to Inter-Branch Transfer order or PO replenishment batch.',
      stockImpact: 'Units remain at source location until marked In-Transit by dispatching facility.',
      moneyImpact: 'Internal transfers have zero external cash impact; logistics freight is logged if applicable.',
      customerOrderImpact: 'Pending customer orders can be linked once specific chassis numbers are dispatched.',
      nextOwner: 'Dispatching Branch Manager or Supplier Procurement Officer.',
      nextCheck: 'Track in Transfers In Transit view for shipment arrival.',
    },
  },

  {
    id: 'scenario-c',
    code: 'SCENARIO-C',
    title: 'End-to-End Procurement Lifecycle (5 Distinct Stages)',
    category: 'Procurement & Finance',
    description: 'Step through the 5 distinct, unbundled stages of commercial procurement: PO, Goods Receipt, Landed Cost, Supplier Bill, and Payment Settlement.',
    segments: [
      {
        id: 'scenario-c-seg-1',
        segmentNumber: 1,
        title: 'Stage 1: Purchase Order Authorisation',
        workspace: 'Super Admin',
        route: '/procurement/orders',
        surface: 'Purchase Orders',
        targetId: 'sa.procurement.orders.action-create-po',
        explanation: 'PO represents contractual intent to purchase EV units or parts from an authorized OEM or supplier at agreed rates.',
        instruction: 'Create and submit the Purchase Order. When approval is required, the order advances from Pending Approval to Approved, and subsequently to Ordered and In Transit upon supplier dispatch.',
        whyItMatters: 'Submitting a PO does NOT create physical stock or record accounts payable.',
        whatHappensNext: 'Supplier manufactures and dispatches units; warehouse awaits arrival.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_2_DRAFT_OR_REVERSIBLE',
      },
      {
        id: 'scenario-c-seg-2',
        segmentNumber: 2,
        title: 'Stage 2: Goods Receipt & Physical Serial Verification',
        workspace: 'Super Admin',
        route: '/procurement/receiving',
        surface: 'Goods Receiving Dock',
        targetId: 'sa.procurement.receiving.action-receive-goods',
        explanation: 'Warehouse verifies physical units against packing list, inspecting battery packs, chargers, and chassis numbers.',
        instruction: 'Record received units and barcode scan individual chassis numbers.',
        whyItMatters: 'Physical stock increases to Available ONLY upon formal Goods Receipt confirmation.',
        whatHappensNext: 'Landed cost allocation screen opens to record freight, customs, and port clearance.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
      {
        id: 'scenario-c-seg-3',
        segmentNumber: 3,
        title: 'Stage 3: Landed Cost Allocation',
        workspace: 'Super Admin',
        route: '/procurement/landed-costs',
        surface: 'Landed Cost Calculator',
        targetId: 'sa.procurement.landed-costs.action-allocate-costs',
        explanation: 'Apportions import duties, carrier logistics, and handling fees across received inventory units.',
        instruction: 'Review freight and clearing invoices, then allocate across unit cost basis.',
        whyItMatters: 'Accurate landed cost calculation ensures true vehicle margin and gross profit reporting.',
        whatHappensNext: 'Supplier Bill is generated matching verified receipt quantities.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
      {
        id: 'scenario-c-seg-4',
        segmentNumber: 4,
        title: 'Stage 4: Supplier Bill Recording',
        workspace: 'Super Admin',
        route: '/finance/supplier-bills',
        surface: 'Supplier Invoices',
        targetId: 'sa.finance.bills.action-create-bill',
        explanation: 'Registers the legal financial liability in Accounts Payable based on the OEM commercial invoice.',
        instruction: 'Verify line items against verified Goods Receipt quantities and book the supplier bill.',
        whyItMatters: 'Supplier Bill booking creates Accounts Payable liability; it does NOT deduct cash.',
        whatHappensNext: 'Bill enters payment scheduling queue.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
      {
        id: 'scenario-c-seg-5',
        segmentNumber: 5,
        title: 'Stage 5: Supplier Payment Settlement',
        workspace: 'Super Admin',
        route: '/finance/payments',
        surface: 'Payment Processing',
        targetId: 'sa.finance.payments.action-record-payment',
        explanation: 'Executes commercial settlement via corporate bank transfer or LC according to agreed payment terms.',
        instruction: 'Record settlement reference, bank disbursement account, and post the payment transaction.',
        whyItMatters: 'Payment reduces Bank Cash balance and clears Accounts Payable liability.',
        whatHappensNext: 'Procurement transaction cycle is fully closed and settled.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_4_SENSITIVE_OR_IRREVERSIBLE',
      },
    ],
    handoff: {
      fromRole: 'Super Admin',
      toRole: 'Super Admin',
      title: 'Procurement Internal Stage Progression',
      whatYouCompleted: 'Executed distinct stages: PO Authorisation -> Goods Receiving -> Cost Capitalisation -> Bill Booking -> Payment Settlement.',
      whatChanged: 'Inventory assets capitalized at landed cost; Accounts Payable liability settled against bank account.',
      nextOwner: 'Finance Controller & Showroom Sales Team',
      whatNextOwnerDoes: 'Reconciles bank statement; showroom sales team can allocate received units to waiting customer orders.',
      whatHasNotHappenedYet: 'Units remain in central warehouse stock until branch transfers are dispatched.',
      whatYouShouldCheckNext: 'Verify asset inventory status displays Available with correct landed cost valuation.',
    },
    debrief: {
      recordImpact: 'Purchase Order, Goods Receipt Note, Landed Cost Voucher, Supplier Bill, and Bank Payment Voucher all archived.',
      stockImpact: 'Serialised inventory incremented with exact chassis and battery IDs in Available status.',
      moneyImpact: 'Cash decreased by payment amount; Asset Inventory increased by base cost + landed logistics expenses.',
      customerOrderImpact: 'Available units can now be allocated to customer reservations.',
      nextOwner: 'Logistics Dispatcher for showroom branch transfers.',
      nextCheck: 'Audit Serialized Asset Inventory ledger to verify serial number fidelity.',
    },
  },

  {
    id: 'scenario-d',
    code: 'SCENARIO-D',
    title: 'Sell an Electric Vehicle (Quotation, Reservation, Payment, Handover)',
    category: 'Sales & Delivery',
    description: 'Walk through showroom sales intake (supporting both Quotation conversion and Direct POS paths), chassis reservation, separate payment, and physical vehicle handover.',
    segments: [
      {
        id: 'scenario-d-seg-1',
        segmentNumber: 1,
        title: 'Customer Quotation or Direct Order Intake',
        workspace: 'Branch Manager',
        route: '/sales/quotations',
        surface: 'Quotations & Sales Intake',
        targetId: 'bm.sales.quotations.action-create-quotation',
        explanation: 'Path A: Draft an itemized quotation for buyer consideration. Path B: Direct Order / Walk-in POS bypasses quotation when customer purchases immediately.',
        instruction: 'Create customer quotation or proceed directly to sales order booking.',
        whyItMatters: 'Quotations are commercial price proposals and do NOT reserve vehicle stock or hold inventory.',
        whatHappensNext: 'When the customer confirms the purchase, an exact physical unit is selected.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_2_DRAFT_OR_REVERSIBLE',
      },
      {
        id: 'scenario-d-seg-2',
        segmentNumber: 2,
        title: 'Sales Order Confirmation & Chassis Reservation',
        workspace: 'Branch Manager',
        route: '/sales/orders',
        surface: 'Sales Orders',
        targetId: 'bm.sales.orders.action-reserve-unit',
        explanation: 'Confirming the order locks the sale. Selecting a specific physical chassis marks the unit as RESERVED.',
        instruction: 'Convert quotation to order and select the exact serial/chassis number from available branch inventory.',
        whyItMatters: 'A sales order only reserves stock when an exact chassis number is assigned; unassigned orders are backorders.',
        whatHappensNext: 'Customer proceeds to deposit or full payment settlement.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
      {
        id: 'scenario-d-seg-3',
        segmentNumber: 3,
        title: 'Payment Intake & Fiscal Receipting',
        workspace: 'Branch Manager',
        route: '/sales/payments',
        surface: 'Payment Receipting',
        targetId: 'bm.sales.payments.action-record-receipt',
        explanation: 'Record initial deposit, installment, or full payment through cash, bank transfer, or financing voucher.',
        instruction: 'Record payment method, amount, and reference number, then generate fiscal receipt.',
        whyItMatters: 'Payment recording is a separate financial step; order reservation is not identical to payment clearance.',
        whatHappensNext: 'Delivery preparation, checklist inspection, and handover scheduling.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_4_SENSITIVE_OR_IRREVERSIBLE',
      },
      {
        id: 'scenario-d-seg-4',
        segmentNumber: 4,
        title: 'Delivery Inspection & Vehicle Handover',
        workspace: 'Branch Manager',
        route: '/sales/handover',
        surface: 'Vehicle Handover & Delivery',
        targetId: 'bm.sales.handover.action-complete-handover',
        explanation: 'Perform standard vehicle delivery checklist inspection, verify charger and documentation, and hand over keys to customer.',
        instruction: 'Confirm inspection checklist, record customer signature, and complete vehicle handover.',
        whyItMatters: 'Handover marks completion of delivery; the unit transitions from Reserved to Sold/customer-owned.',
        whatHappensNext: 'Warranty period initiates and revenue/COGS entries are finalized in financial ledger.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
    ],
    handoff: {
      fromRole: 'Branch Manager',
      toRole: 'Branch Manager',
      title: 'Showroom Delivery & Post-Sale Care',
      whatYouCompleted: 'Completed sales intake (quotation or direct POS), order confirmation, chassis reservation, payment intake, and vehicle handover.',
      whatChanged: 'Unit status updated to Sold/customer-owned; customer registered as vehicle owner; warranty registered.',
      nextOwner: 'Showroom Service Specialist & Finance Auditor',
      whatNextOwnerDoes: 'Schedules first complimentary inspection; reconciles showroom daily sales drawer.',
      whatHasNotHappenedYet: 'Registration authority documentation is processed through customer local excise office.',
      whatYouShouldCheckNext: 'Verify sales invoice copy is filed and handover protocol is uploaded to customer record.',
    },
    debrief: {
      recordImpact: 'Sales Order marked COMPLETED; Payment Receipts posted; Handover Protocol archived.',
      stockImpact: 'Selected chassis transitioned from RESERVED to Sold/customer-owned; branch available EV count reduced by 1.',
      moneyImpact: 'Cash / Bank balance debited; Sales Revenue credited; COGS recognized against inventory asset account.',
      customerOrderImpact: 'Customer record updated with vehicle ownership history and active warranty coverage.',
      nextOwner: 'Showroom Workshop for scheduled service visits.',
      nextCheck: 'Audit daily cash and bank reconciliation report in Finance module.',
    },
  },

  {
    id: 'scenario-e',
    code: 'SCENARIO-E',
    title: 'Controlled Inventory Discrepancy & Adjustment',
    category: 'Inventory Governance',
    description: 'Learn the strict three-stage procedure for managing inventory variances: showroom cycle count discovery, Head Office investigation & authorization, followed by controlled adjustment posting.',
    segments: [
      {
        id: 'scenario-e-seg-1',
        segmentNumber: 1,
        title: 'Branch Cycle Count & Variance Discovery',
        workspace: 'Branch Manager',
        route: '/inventory/cycle-counts',
        surface: 'Cycle Counts',
        targetId: 'bm.inventory.cycle-counts.action-submit-count',
        explanation: 'Showrooms conduct routine physical counts of batteries, tyres, and spare parts against system ledgers.',
        instruction: 'Record physical count and document reason for any discovered shortage or damaged part.',
        whyItMatters: 'Recording a count variance is an audit observation; it does NOT automatically adjust inventory or post write-offs.',
        whatHappensNext: 'Discrepancy is submitted as an Inventory Adjustment Request to Super Admin.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_2_DRAFT_OR_REVERSIBLE',
      },
      {
        id: 'scenario-e-seg-2',
        segmentNumber: 2,
        title: 'Super Admin Discrepancy Investigation & Authorization',
        workspace: 'Super Admin',
        route: '/inventory/adjustments',
        surface: 'Inventory Adjustments Queue',
        targetId: 'sa.inventory.adjustments.action-approve-adjustment',
        explanation: 'Super Admin investigates variance cause (theft, transit loss, damage, count error) and authorizes write-off/write-on.',
        instruction: 'Review root-cause documentation and approve or reject the adjustment request.',
        whyItMatters: 'Adjustment approval is required before posting; approval authorizes adjustment but does NOT post to general ledger.',
        whatHappensNext: 'Authorized adjustment advances to controlled posting stage.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
      {
        id: 'scenario-e-seg-3',
        segmentNumber: 3,
        title: 'Controlled Adjustment Posting Workflow',
        workspace: 'Super Admin',
        route: '/inventory/adjustments',
        surface: 'Inventory Adjustments Posting',
        targetId: 'sa.inventory.adjustments.action-post-adjustment',
        explanation: 'After authorization, the adjustment advances to the separate authorized posting workflow in the Super Admin workspace. Creator, approver, and posting actor identities remain distinct audit records.',
        instruction: 'Verify authorized quantities and confirm posting to inventory accounts.',
        whyItMatters: 'Posting permanently synchronizes system balance with verified physical stock and books write-off expense; approval and posting remain separate operational responsibilities.',
        whatHappensNext: 'Branch stock balance is synchronized with physical reality.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_4_SENSITIVE_OR_IRREVERSIBLE',
      },
    ],
    handoff: {
      fromRole: 'Branch Manager',
      toRole: 'Super Admin',
      title: 'Handoff to Internal Audit & Inventory Control',
      whatYouCompleted: 'Conducted physical count, documented discrepancy, and submitted formal adjustment request.',
      whatChanged: 'Adjustment request logged as PENDING_AUDIT in central inventory control queue.',
      nextOwner: 'Super Admin / Inventory Controller',
      whatNextOwnerDoes: 'Investigates discrepancy history, verifies security logs, and approves or rejects adjustment before posting.',
      whatHasNotHappenedYet: 'Stock ledger quantities have not changed and no financial write-off has posted.',
      whatYouShouldCheckNext: 'Check Adjustment status for authorization and posting notes.',
    },
    debrief: {
      recordImpact: 'Adjustment voucher APPROVED and POSTED with full audit trail and reason code.',
      stockImpact: 'Branch stock balance corrected to match verified physical count.',
      moneyImpact: 'Inventory shrinkage expense recorded in P&L; asset inventory valuation reduced accordingly.',
      customerOrderImpact: 'Prevents phantom inventory from appearing available for customer orders.',
      nextOwner: 'Branch Manager for continuous shelf audit adherence.',
      nextCheck: 'Run Inventory Valuation Report to confirm corrected balance.',
    },
  },

  {
    id: 'scenario-f',
    code: 'SCENARIO-F',
    title: 'Operating Expense Authorization & Settlement',
    category: 'Finance & Branch Control',
    description: 'Understand the multi-stage control on operational disbursements: branch expense logging, Head Office approval, followed by separate cash/bank payout.',
    segments: [
      {
        id: 'scenario-f-seg-1',
        segmentNumber: 1,
        title: 'Showroom Expense Claim Submission',
        workspace: 'Branch Manager',
        route: '/finance/expenses',
        surface: 'Branch Expenses',
        targetId: 'bm.finance.expenses.action-create-claim',
        explanation: 'Branch Managers record utility bills, facility maintenance, local marketing, or showroom cleaning expenses.',
        instruction: 'Upload invoice receipt, select expense category, and submit for reimbursement or vendor settlement.',
        whyItMatters: 'Submitting an expense claim is NOT approval and does not authorize cash disbursement.',
        whatHappensNext: 'Claim appears in Head Office Expense Approval queue.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_2_DRAFT_OR_REVERSIBLE',
      },
      {
        id: 'scenario-f-seg-2',
        segmentNumber: 2,
        title: 'Head Office Expense Review & Authorization',
        workspace: 'Super Admin',
        route: '/finance/expenses',
        surface: 'Central Expense Queue',
        targetId: 'sa.finance.expenses.action-approve-expense',
        explanation: 'Finance Director / Super Admin verifies receipt legitimacy, budget headroom, and authorizes expenditure.',
        instruction: 'Review attached receipt and approve the expense claim.',
        whyItMatters: 'Expense approval authorizes expense recognition against budget; disbursing cash is a separate payment step.',
        whatHappensNext: 'Approved voucher advances to disbursement payment queue.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_3_BUSINESS_RECORD_MUTATION',
      },
      {
        id: 'scenario-f-seg-3',
        segmentNumber: 3,
        title: 'Authorized Disbursement & Payment Settlement',
        workspace: 'Super Admin',
        route: '/finance/expenses',
        surface: 'Expense Disbursement',
        targetId: 'sa.finance.expenses.action-record-payout',
        explanation: 'After approval, payment/recording continues through the separate authorized finance disbursement workflow. Approver and payer identities remain distinct audit records.',
        instruction: 'Select disbursement account, record bank reference or cash voucher, and post payment.',
        whyItMatters: 'Posting payment reduces cash/bank balance and closes the accounts payable voucher; approval and payment disbursement remain separate financial responsibilities.',
        whatHappensNext: 'General ledger records expense in branch P&L and reduces cash/bank balance.',
        expectedAction: 'CLICK',
        mutationRisk: 'RISK_4_SENSITIVE_OR_IRREVERSIBLE',
      },
    ],
    handoff: {
      fromRole: 'Branch Manager',
      toRole: 'Super Admin',
      title: 'Handoff to Finance & Accounts Department',
      whatYouCompleted: 'Submitted itemized expense claim with supplier invoice and receipt attached.',
      whatChanged: 'Expense claim status is now PENDING_APPROVAL in central accounts.',
      nextOwner: 'Super Admin / Accounts Payable Officer',
      whatNextOwnerDoes: 'Verifies compliance, checks showroom budget threshold, and issues payment authorization followed by disbursement.',
      whatHasNotHappenedYet: 'Cash has not been disbursed and petty cash float has not been reimbursed.',
      whatYouShouldCheckNext: 'Check expense status for approval and reimbursement notification.',
    },
    debrief: {
      recordImpact: 'Expense voucher APPROVED and PAID; voucher archived with attached receipt.',
      stockImpact: 'Zero stock impact. Pure operational financial transaction.',
      moneyImpact: 'Operating Expense recognized in branch P&L; Cash/Bank asset account decreased by disbursement amount.',
      customerOrderImpact: 'Zero impact on customer orders.',
      nextOwner: 'Branch Cashier to file physical receipt copy.',
      nextCheck: 'Verify expense entry in Monthly Branch Income Statement.',
    },
  },
];
